POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQwODkzOTExLCJ1c2VySWQiOjF9.dABXNTbZAqAkmmpBmJoNsnZZdnlsNv7pInzHvw1a1-E

{
    "name": "Test Event",
    "description": "This is a test event.",
    "location": "New York",
    "dateTime": "2025-01-01T12:00:00Z"
}