DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0MDg5NTcyMSwidXNlcklkIjoyfQ.KmTMMz_qvkr2fWn_Bpqdv8k9s3hRverJSP9-HkYm5Es