PUT http://localhost:8080/events/2
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0MDg5NTcyMSwidXNlcklkIjoyfQ.KmTMMz_qvkr2fWn_Bpqdv8k9s3hRverJSP9-HkYm5Es

{
    "name": "Test Event edit",
    "description": "This is a test edit event.",
    "location": "Chicago",
    "dateTime": "2025-01-01T12:00:00Z"
}