PUT http://localhost:8080/events/3
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQwODkzOTExLCJ1c2VySWQiOjF9.dABXNTbZAqAkmmpBmJoNsnZZdnlsNv7pInzHvw1a1-E

{
    "name": "Test Event edit",
    "description": "This is a test edit event.",
    "location": "Chicago",
    "dateTime": "2025-01-01T12:00:00Z"
}